// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF5LP7dFq3KBwRVT8EO_0DWOgJ87spjRQ',
    appId: '1:776660339631:android:ade29338a88973319e7d5a',
    messagingSenderId: '776660339631',
    projectId: 'saveit-app-1784d',
    storageBucket: 'saveit-app-1784d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVIjnCAqi8gIy1sYpVMX-DSCMfwvFgptk',
    appId: '1:776660339631:ios:ac36b2aba03689b49e7d5a',
    messagingSenderId: '776660339631',
    projectId: 'saveit-app-1784d',
    storageBucket: 'saveit-app-1784d.firebasestorage.app',
    androidClientId:
        '776660339631-bppg6krpb2n0jr9o45skr4b7fqha977i.apps.googleusercontent.com',
    iosClientId:
        '776660339631-qhgsdg8vin4gabllbbgd5526bffivosp.apps.googleusercontent.com',
    iosBundleId: 'eu.savein.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgHK8zKBpFy1dQZQ0_z0iNZ6Nr3j7ksPU',
    appId: '1:776660339631:web:57dddde13817a4af9e7d5a',
    messagingSenderId: '776660339631',
    projectId: 'saveit-app-1784d',
    authDomain: 'saveit-app-1784d.firebaseapp.com',
    storageBucket: 'saveit-app-1784d.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVIjnCAqi8gIy1sYpVMX-DSCMfwvFgptk',
    appId: '1:776660339631:ios:016628f9f46386629e7d5a',
    messagingSenderId: '776660339631',
    projectId: 'saveit-app-1784d',
    storageBucket: 'saveit-app-1784d.firebasestorage.app',
    androidClientId:
        '776660339631-da84644ndhbv3q5l5h3m9hl9tuv9mpgq.apps.googleusercontent.com',
    iosClientId:
        '776660339631-utpt8pbescr42c5ir4eg9kt68nkalahs.apps.googleusercontent.com',
    iosBundleId: 'com.example.saveit',
  );
}
